{% set name = "gradio-client" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gradio_client-{{ version }}.tar.gz
  sha256: 5f7f8c25c7d963a3ec805e135030a2283eea49dd4fc0c69c6b119ae56b33bc6b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling
    - hatch-requirements-txt
    - hatch-fancy-pypi-readme >=22.5.0
    - pip
  run:
    - python >=3.8
    - fsspec
    - httpx
    - huggingface_hub >=0.13.0
    - packaging
    - requests ~=2.0
    - typing_extensions ~=4.0
    - websockets >=10.0,<12.0

test:
  imports:
    - gradio_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/gradio-client/
  dev_url: https://github.com/gradio-app/gradio
  summary: Python library for easily interacting with trained machine learning models
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Sclare87
