schema_version: 1

context:
  version: "2.7.0"

package:
  name: gradio-client
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/g/gradio-client/gradio_client-${{ version }}.tar.gz
  sha256: 212c88f7f6a212c973b4429ec450b35efba7805a34aee53f0892535ceee194ae

build:
  noarch: python
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - hatch-requirements-txt
    - hatch-fancy-pypi-readme >=22.5.0
    - pip
  run:
    - python >=${{ python_min }}
    - fsspec
    - httpx >=0.24.1
    - huggingface_hub >=0.19.3,<2.0
    - packaging
    - typing_extensions ~=4.0

tests:
  - python:
      imports:
        - gradio_client
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - >-
        python -c "from gradio_client import handle_file; data = handle_file('https://example.com/input.txt'); assert data['orig_name'] == 'input.txt'; assert data['url'] == 'https://example.com/input.txt'"

about:
  homepage: https://pypi.org/project/gradio-client/
  repository: https://github.com/gradio-app/gradio
  summary: Python library for easily interacting with trained machine learning models
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeongseok-meta
    - abidlabs
    - Sclare87
